# Generated by Django 4.2.2 on 2023-07-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_issue_mechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='mechanic',
        ),
    ]
