# Generated by Django 4.2.2 on 2023-07-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_issue_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='myapp.agent'),
        ),
        migrations.AddField(
            model_name='issue',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='myapp.mechanic'),
        ),
    ]
